import Image from "next/image";
import { RequestForm } from "@/components/RequestForm";
import { site } from "@/lib/site";

const services: [string, string, string[]][] = [
  ["01", "Ремонт ходовой", ["Ремонт подвески", "Рулевое управление", "Тормозная система"]],
  ["02", "Замена масла", ["Аппаратная замена масла", "Масла и фильтры со склада", "Проверка уровней"]],
  ["03", "Диагностика", ["Компьютерная диагностика", "Диагностика ходовой", "Подготовка к поездке"]],
  ["04", "Двигатель и АКПП", ["Поиск причины неисправности", "Ремонт агрегатов", "Согласование до работ"]],
  ["05", "Климат и электрика", ["Обслуживание кондиционера", "Проверка электрики", "Поиск утечек"]],
  ["06", "Кузовной SMART-ремонт", ["Локальные вмятины", "Бамперы и царапины", "Подбор решения"]],
];
const why = [["Собственный склад", "Масла, фильтры и расходники можно подобрать на месте."], ["Спецоборудование", "Тёплый бокс и оборудование для точной диагностики."], ["Смета до ремонта", "Работы и запчасти согласовываем до начала ремонта."], ["Удобная оплата", "Наличные, карта, перевод или QR — как удобно вам."]];
const visit = [["Заявка", "Звонок, WhatsApp, Telegram или форма на сайте."], ["Диагностика", "Осмотр автомобиля и компьютерная проверка по запросу."], ["Согласование", "Фиксируем работы, сроки и стоимость до ремонта."], ["Ремонт", "Выполняем только согласованный объём работ."], ["Контроль", "Проверяем узлы и результат после ремонта."], ["Выдача", "Объясняем, что сделали, и даём гарантию."]];

export default function Home() {
  return <>
    <section className="reference-hero"><div className="reference-container reference-hero-grid"><div className="reference-hero-copy"><div className="reference-kicker"><span className="reference-dot"/>МОНСТР ТРЕК · АВТОСЕРВИС В АЛМАТЫ</div><h1>Автосервис,<br/><em>которому доверяют.</em></h1><p>Ходовая, диагностика, масло, климат и агрегаты. Объясняем проблему человеческим языком и согласовываем ремонт до начала работ.</p><div className="reference-hero-actions"><a className="reference-orange" href="#request">Записаться на сервис</a><a className="reference-phone" href={site.phoneHref}>{site.phone}</a></div><div className="reference-proof"><b>4.9 ★</b><span>Отзывы клиентов</span><b>7+</b><span>лет в сервисе</span><b>09:00–20:00</b><span>Пн–Сб</span></div></div><div className="reference-hero-image"><Image src="/brand/monster-truck-hero.jpg" alt="Монстр Трек — автосервис" fill priority sizes="(max-width:900px) 100vw, 50vw"/><div className="reference-image-caption">Работы в боксе Монстр Трек<br/><small>Проверяем · объясняем · ремонтируем</small></div></div></div></section>
    <section id="services" className="reference-section reference-container"><div className="reference-section-head"><span>01 / Услуги</span><h2>Что делаем</h2><p>Основные направления сервиса. Нажмите на блок, чтобы записаться.</p></div><div className="reference-service-grid">{services.map(([n,title,items])=><a className="reference-service" href="#request" key={n}><span className="reference-number">{n}</span><h3>{title}</h3><ul>{(items as string[]).map(item=><li key={item}>{item}</li>)}</ul><strong>Записаться <span>→</span></strong></a>)}</div></section>
    <section className="reference-feature"><div className="reference-container feature-grid"><div className="feature-photo"><Image src="/brand/monster-truck-hero.jpg" alt="Аппаратная замена масла" fill sizes="(max-width:900px) 100vw, 45vw"/></div><div><span className="reference-accent">Акцент</span><h2>Аппаратная<br/>замена масла</h2><p>Отдельное направление сервиса. Подбираем масло и фильтры под двигатель, объясняем интервалы и фиксируем работу в заказ-наряде.</p><a href="#request" className="reference-dark-button">Записаться →</a></div></div></section>
    <section className="reference-section reference-container"><div className="reference-section-head"><span>02 / Почему мы</span><h2>Почему Монстр Трек</h2></div><div className="reference-why-grid">{why.map(([title,text])=><div className="reference-why" key={title}><b>{title}</b><p>{text}</p></div>)}</div><div className="reference-brands"><span>Масла и расходники, которые знаем:</span><b>LIQUI MOLY</b><b>MOBIL</b><b>ENEOS</b><b>TOYOTA</b><b>MANN</b><b>BOSCH</b></div></section>
    <section className="reference-gallery"><div className="reference-container"><div className="reference-section-head"><span>03 / Сервис</span><h2>Вот где будет<br/>ваш автомобиль</h2><p>Прозрачная работа в оборудованном боксе.</p></div><div className="reference-gallery-grid"><div className="gallery-large"><Image src="/brand/monster-truck-hero.jpg" alt="Автомобиль в боксе Монстр Трек" fill sizes="60vw"/></div><div className="gallery-card"><div className="gallery-swatch orange-swatch"/><b>Фасад и въезд</b><span>Удобный заезд с улицы</span></div><div className="gallery-card"><div className="gallery-swatch dark-swatch"/><b>Подъёмник и диагностика</b><span>Работаем по чек-листу</span></div></div></div></section>
    <section className="reference-section reference-container"><div className="reference-section-head"><span>04 / Визит</span><h2>Как проходит визит</h2></div><div className="reference-visit-grid">{visit.map(([title,text],i)=><div key={title}><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>
    <section className="reference-review"><div className="reference-container review-layout"><div><span className="reference-accent">05 / Отзывы клиентов</span><div className="review-score">4.9 <span>★</span></div><b>★★★★★</b><p>Отзывы о Монстр Трек — это конкретные автомобили и конкретная работа.</p><a href="#request">Оставить заявку →</a></div><blockquote>«Показали машину на подъёмнике и спокойно объяснили, что действительно нужно сделать. Смета не изменилась, лишнего не навязывали. Теперь обслуживаю машину только здесь.»<cite>— Алексей · Toyota Camry · подтверждённый клиент</cite></blockquote></div></section>
    <section id="request" className="reference-form-section"><div className="reference-container"><div className="reference-section-head"><span>06 / Запись</span><h2>Нужен ремонт?</h2><p>Запишитесь в Монстр Трек. Перезвоним или ответим в WhatsApp.</p></div><div className="reference-form-shell"><div className="form-contact"><b>{site.phone}</b><span>{site.address}</span><span>{site.hours}</span><div><a href={site.phoneHref}>Позвонить</a><a href={site.whatsappUrl}>WhatsApp</a></div></div><RequestForm source="reference-home"/></div></div></section>
    <section id="contacts" className="reference-contact"><div className="reference-container contact-grid"><div><span>07 / Контакты</span><h2>Монстр Трек</h2><p>{site.address}<br/>Алматы</p></div><div><a className="contact-phone" href={site.phoneHref}>{site.phone}</a><p>{site.hours}</p><div className="contact-links"><a href={site.phoneHref}>Позвонить</a><a href={site.whatsappUrl}>WhatsApp</a><a href={site.telegramUrl}>Telegram</a></div></div></div></section>
  </>;
}
